### ISSUE TITLE
makeBOJFolder 타이틀 파싱 실패

### ISSUE THREAD

**Issue by alsrua7222** [alsrua7222/BOJ_Algorithm_Study#1]
Traceback (most recent call last):
  File "C:\Users\KMK\PycharmProjects\selenium\makeBOJFolder.py", line 49, in <module>
    makeReadMeFile(NUMBER, BLOG_PATH)
  File "C:\Users\KMK\PycharmProjects\selenium\makeBOJFolder.py", line 36, in makeReadMeFile
    title = re.findall("<title>[0-9]+번: (.*?)</title>", requests.get(url).text)[0]
IndexError: list index out of range

title = 타이틀에 대한 html 구조에 문제 있는 것으로 보임.

**Comment by alsrua7222** [comment]
해결 완료
